### ISSUE TITLE
Tilde is not expanded in "pytest" setting

### ISSUE THREAD

**Issue by sprat** [kaste/PyTest#35]
The tilde is not expanded in the "pytest" setting, so I should hardcode my home directory for the plugin to work ("~/.virtualenvs/${project_base_name}/Scripts/pytest.exe" does not work)

**Comment by kaste** [comment]
Yes that's correct.  Only Sublime variables are expanded atm; should be the same functionality as Sublime's "build systems".

**Comment by sprat** [comment]
I mean, I consider this as a bug since the default settings file show an example with a tilde. And it's important for me since I use the same settings on different machines with a different account username, and it prevents reusing the same settings in my use-case.

**Comment by kaste** [comment]
Lol, yes the README has it.  Should be added here

https://github.com/kaste/PyTest/blob/04a4c698186f68c3ea7085746f121e3e007db17c/PyTest.py#L144-L149

**Comment by sprat** [comment]
Many thanks!

**Comment by sprat** [comment]
Oh, the plugin is now broken:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1456, in run_
    return self.run(**args)
  File "C:\Users\sprat\AppData\Roaming\Sublime Text\Installed Packages\PyTest.sublime-package\PyTest.py", line 116, in run
  File "C:\Users\sprat\AppData\Roaming\Sublime Text\Installed Packages\PyTest.sublime-package\PyTest.py", line 151, in _expand
  File "./python3.3/ntpath.py", line 311, in expanduser
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by kaste** [comment]
Ah. It's like Friday just on Thursday.
